apiVersion: 1

datasources:
  - name: Prometheus
    uid: hdb-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Tempo
    uid: hdb-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: hdb-loki
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        tags: [{key: service.name, value: service_name}]
      tracesToMetrics:
        datasourceUid: hdb-prometheus
  - name: Loki
    uid: hdb-loki
    type: loki
    access: proxy
    url: http://loki:3100
