"""Versioned, format-neutral planning contracts for document authoring.

The planning package is intentionally independent from the current execution
graph.  It contains the values that a planner may persist and the validation
needed before a proposal can be confirmed.
"""

from .models import (
    ArtifactSpec,
    AffectedSubgraph,
    CoverageContract,
    CoverageRequirement,
    DependencyEdge,
    DeliverableSpec,
    DocumentPlan,
    GeneratedStructureSource,
    LayoutContract,
    LayoutSource,
    OutlineUnitSpec,
    OutputSpec,
    PlanDiff,
    PlanIssue,
    ProvidedTemplateSource,
    SemanticUnitPlan,
    SourceScopeSpec,
    StructureContract,
    SystemRecipeSource,
    TableRequirement,
    TemplateContract,
    UnitTaskSpec,
    planning_content_hash,
)
from .registry import (
    CapabilityRegistries,
    DomainStrategy,
    DomainStrategyDescriptor,
    DomainStrategyRegistry,
    LayoutAdapter,
    LayoutAdapterDescriptor,
    LayoutAdapterRegistry,
    RendererCapability,
    RendererCapabilityDescriptor,
    RendererCapabilityRegistry,
    build_builtin_registries,
)
from .sources import FrozenSourceRef, FrozenSourceScope, SourceType
from .diff import compile_affected_subgraph, diff_document_plans
from .legacy import legacy_brief_to_output_spec
from .service import DocumentPlanningService, LegacyTemplatePlanningAdapter, TemplateFreePlanningAdapter
from .recipes import (
    RecipeComponent,
    RecipeRegistry,
    StructureBindingCompiler,
    StructureBindingSet,
    StructureConstraintsProfile,
    StructureProfile,
    StructureProfileRegistry,
    StructureRenderBinding,
    SystemRecipe,
    build_builtin_recipe_registry,
    build_builtin_structure_profile_registry,
)
from .intake import IntakeQuestion, OutputSpecIntakeService, OutputSpecVersionConflict
from .coverage import CoverageEvaluator
from .review_contracts import (
    CoverageReport,
    CoverageRequirementResult,
    RequirementCoverageResult,
    ReviewIssue,
    UnitReviewResult,
    safe_review_projection,
)
from .unit_review import UnitReviewer
from .artifact_review import ArtifactReviewReport, ArtifactReviewer
from .document_review import (
    DocumentReleaseGate,
    DocumentReviewReport,
    DocumentReviewer,
    DocumentReworkRouter,
    ReleaseDecision,
    ReworkDecision,
)
from .strategies import (
    DocumentDomainStrategy,
    DomainRequirements,
    FptStrategy,
    GenericReportStrategy,
    IcdStrategy,
    RequirementsStrategy,
    build_builtin_domain_strategies,
)
from .release import (
    ApprovalPolicy,
    ApprovalPolicyRegistry,
    ArtifactLineage,
    GateFact,
    PolicyReleaseDecision,
    ReleasePolicyService,
    ReleaseSignature,
    TenantReleasePolicy,
    build_builtin_approval_policy_registry,
    reconstruct_artifact_lineage,
)

__all__ = [
    "ArtifactSpec",
    "AffectedSubgraph",
    "CoverageContract",
    "CoverageRequirement",
    "DependencyEdge",
    "DeliverableSpec",
    "DocumentPlan",
    "GeneratedStructureSource",
    "LayoutContract",
    "LayoutSource",
    "OutlineUnitSpec",
    "OutputSpec",
    "PlanDiff",
    "PlanIssue",
    "ProvidedTemplateSource",
    "SemanticUnitPlan",
    "SourceScopeSpec",
    "StructureContract",
    "SystemRecipeSource",
    "TableRequirement",
    "TemplateContract",
    "UnitTaskSpec",
    "planning_content_hash",
    "CapabilityRegistries",
    "DomainStrategy",
    "DomainStrategyDescriptor",
    "DomainStrategyRegistry",
    "FrozenSourceRef",
    "FrozenSourceScope",
    "LayoutAdapter",
    "LayoutAdapterDescriptor",
    "LayoutAdapterRegistry",
    "RendererCapability",
    "RendererCapabilityDescriptor",
    "RendererCapabilityRegistry",
    "SourceType",
    "build_builtin_registries",
    "diff_document_plans",
    "compile_affected_subgraph",
    "DocumentPlanningService",
    "LegacyTemplatePlanningAdapter",
    "TemplateFreePlanningAdapter",
    "RecipeComponent",
    "RecipeRegistry",
    "StructureBindingCompiler",
    "StructureBindingSet",
    "StructureConstraintsProfile",
    "StructureProfile",
    "StructureProfileRegistry",
    "StructureRenderBinding",
    "SystemRecipe",
    "build_builtin_recipe_registry",
    "build_builtin_structure_profile_registry",
    "legacy_brief_to_output_spec",
    "IntakeQuestion",
    "OutputSpecIntakeService",
    "OutputSpecVersionConflict",
    "CoverageEvaluator",
    "CoverageReport",
    "CoverageRequirementResult",
    "RequirementCoverageResult",
    "ReviewIssue",
    "UnitReviewer",
    "UnitReviewResult",
    "safe_review_projection",
    "ArtifactReviewReport",
    "ArtifactReviewer",
    "DocumentReleaseGate",
    "DocumentReviewReport",
    "DocumentReviewer",
    "DocumentReworkRouter",
    "ReleaseDecision",
    "ReworkDecision",
    "DocumentDomainStrategy",
    "DomainRequirements",
    "FptStrategy",
    "GenericReportStrategy",
    "IcdStrategy",
    "RequirementsStrategy",
    "build_builtin_domain_strategies",
    "ApprovalPolicy",
    "ApprovalPolicyRegistry",
    "ArtifactLineage",
    "GateFact",
    "PolicyReleaseDecision",
    "ReleasePolicyService",
    "ReleaseSignature",
    "TenantReleasePolicy",
    "build_builtin_approval_policy_registry",
    "reconstruct_artifact_lineage",
]
